Load from config if cached user file corrupted
There's a particular scenario where the pickled user cannot be loaded,
producing this error:

```
➜  pnc-cli git:(version-1.3.x) ✗ pnc get-repository-configuration '10'
Traceback (most recent call last):
  File "/usr/bin/pnc", line 11, in <module>
    load_entry_point('pnc-cli==1.3.6', 'console_scripts', 'pnc')()
  File "build/bdist.linux-x86_64/egg/pnc_cli/pnc.py", line 137, in main
  File "/usr/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "build/bdist.linux-x86_64/egg/pnc_cli/repositoryconfigurations.py", line 18, in get_repository_configuration
  File "build/bdist.linux-x86_64/egg/pnc_cli/pnc_api.py", line 138, in repositories
  File "build/bdist.linux-x86_64/egg/pnc_cli/pnc_api.py", line 48, in user
  File "build/bdist.linux-x86_64/egg/pnc_cli/user_config.py", line 176, in get_user
  File "/usr/lib64/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "build/bdist.linux-x86_64/egg/pnc_cli/user_config.py", line 53, in __setstate__
ValueError: too many values to unpack
```

This might happen because the pickled file changed format or object
changed in between PNC versions. In those cases, we should delete the
pickle file and load from config instead to invalidate the
'cached/pickled' file/object.